parameters:
  ivao.whazzup.fileUrl: 'https://api.ivao.aero/v2/tracker/whazzup'
services:
  whazzup.client:
    class: IvaoPHP\Whazzup\Http\WhazzupClient
    arguments: ['@infrastructure.http.fileDownloader', '%ivao.whazzup.fileUrl%']
  infrastructure.http.fileDownloader:
    class: IvaoPHP\Infrastructure\Http\FileDownloader